site_name: work_tools Docs
theme:
  name: material
site_url: ""
use_directory_urls: false
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_inheritance_diagram: true
            docstring_options:
              ignore_init_summary: false
          rendering:
            show_source: true
