site_name: work_tools Docs
theme:
  name: material
site_url: ""
use_directory_urls: false
plugins:
  - search
  - mkdocstrings:
      watch:
        - work_tools
      handlers:
        python:
          rendering:
            show_source: true
